services:
  college: #nombre de la app establecido en application.properties
    build: college #nombre de la carpeta donde está el DockerFile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://collegeserver:3306/collegedbt?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      collegeserver:
          condition: service_healthy
  collegeserver: #configuraciones de base de datos dockerizada
    image: mysql:9.5.0 #misma versión que esté en el pom
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: collegedbt
      MYSQL_PASSWORD: 1234
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: college_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: collegeserver
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
      UPLOAD_LIMIT: 300M
    depends_on:
       - collegeserver

volumes:
  mysql_data: